### ISSUE TITLE
32-bit pylsd-nova - ImportError: Cannot load dynamic library. Did you compile LSD?

### ISSUE THREAD

**Issue by n0spaces** [n0spaces/get-stick-bugged-lol#1]
I tried installing this on another Windows computer and now I keep getting this ImportError whenever pylsd is imported. May need to switch to a different library if no fix is available.

**Comment by NexInfinite** [comment]
Yeah im having the same issue here

**Comment by NexInfinite** [comment]
pylsd is not supported in python 3, that's your issue. Ill see if I can find a fix

**Comment by n0spaces** [comment]
I'm using [pylsd-nova](https://github.com/AndranikSargsyan/pylsd-nova), which does have python 3 support. This works fine on my computer running Windows and python 3.8, but not on a computer at my school running the same thing.
There's another py3 fork called [ocrd-fork-pylsd](https://pypi.org/project/ocrd-fork-pylsd/). Can you try using that instead and see if it makes any difference?
```
pip uninstall pylsd-nova
pip install ocrd-fork-pylsd
```

**Comment by NexInfinite** [comment]
Sure Ill give it a go, I tried to use pylsd-nova but I am running python 3.6 and it didn't work; could be something up there.

**Comment by NexInfinite** [comment]
Just tried now and it didn't import, gonna try use pylsd-nova on python 3.8.5

**Comment by millieTime** [comment]
I have the same error, and had the same results from trying ocrd-ford-pylsd =(

**Comment by NexInfinite** [comment]
Switching to python 3.8.5 hasn't helped. I'm gonna see if I can figure out why

**Comment by millieTime** [comment]
I don't have experience with python, but I found this StackExchange question, does it help? https://stackoverflow.com/questions/52288690/pyinstaller-unable-to-import-pylsd-while-creating-exe-file

**Comment by NexInfinite** [comment]
Yeah I've just noticed that its looking for a lib called `lsd` and I can't find one on pypi. There is a `lsd` lib but its for converting currencies

**Comment by NexInfinite** [comment]
The issue is coming from `pylsd-nova` as `ocrd-pylsd-fork` does not have this issue. But it has its own issues. A little confusing and the person who made `pylsd` hasn't responded to any of the issues that people have flagged since 2018

**Comment by millieTime** [comment]
shoot. Is there another library we can use?

**Comment by NexInfinite** [comment]
I dont think so, but I've just noticed that it uses c++ and c and so maybe its got something to do with that. I don't have either installed with visual studio so I'm gonna install and see if it fixes anything

**Comment by NexInfinite** [comment]
I think I have found the issue, I am on x86 and pylsd is looking for a dir called `win32/x86/lsd.dll` but for some reason there is only `win32/x64/lsd.dll` @n0spaces may be on x64 and that's why its working for him.

**Comment by NexInfinite** [comment]
![image](https://user-images.githubusercontent.com/37962677/90315432-75af0b00-df13-11ea-9379-b28541606794.png)

**Comment by millieTime** [comment]
Looking into that, I found this article: https://stackoverflow.com/questions/27816562/what-does-struct-calcsizep-exactly-mean

If it will fix the problem, could we / how do we change the line 'if sys.maxsize > 2 ** 32:' to 'if struct.calcsize('P') > 5:'  (also very new to Git =)

**Comment by NexInfinite** [comment]
Ill give it a go when I'm back at my pc

**Comment by NexInfinite** [comment]
So I can change it, but we will need to include it in the repo or maybe make a fork of it or something. Dont fully know how that would work either

**Comment by Yunusa13** [comment]
So, have you found any solutions?

**Comment by n0spaces** [comment]
Since pylsd isn't compatible with Windows 32-bit versions of Python, right now the solution is to just use 64-bit Python instead. AFAIK the only thing stopping pylsd from working on 32-bit Python is a missing lsd.dll file for x86, so I'll see if that's something that can be compiled.

**Comment by thunderkai** [comment]
quick question, i had this problem until i downloaded 64bit version, now where do i put the image i wanna meme (input.png)?

**Comment by n0spaces** [comment]
@thunderkai Glad to know it's working. The image can be wherever you want, you just have to make sure it's in your current directory in the terminal or use the full file path in the command.
`gsbl C:\path\to\input.png C:\path\to\output.mp4`
Also if you have any questions that aren't relevant to this issue, please open a new one and ask there.

**Comment by NexInfinite** [comment]
Im gonna try with 64 bit

**Comment by NexInfinite** [comment]
https://github.com/AndranikSargsyan/pylsd-nova/issues/1 Pylsd has been upgraded to support x86

**Comment by millieTime** [comment]
Awesome! I just pip uninstall pylsd-nova and pip install pylsd-nova and it works perfectly!

**Comment by NexInfinite** [comment]
That update has fixed it! Nice work everyone

**Comment by n0spaces** [comment]
requirements.txt still forces pylsd-nova 1.0.0 to be installed. I'll fix that tonight and release a new version.

Also FYI `pip install --upgrade pylsd-nova` should also work.

Thanks for the help everyone!

**Comment by NexInfinite** [comment]
Yeah, and if you are using pycharm you can go to `setting > project interpreter > PROJECT_NAME > pylsd-nova` and click the triangle on the right bar to upgrade. Pycharms project management is very useful.

**Comment by AndranikSargsyan** [comment]
I found this repo through the opened issue on pylsd-nova repository. Really nice meme generator :D By the way, you can get better line segments by playing with `lsd` parameters via pylsd-nova's binding. For example you can try to change `scale` parameter like this `segments = lsd(im_gray, scale=0.4)`. There are many other parameters described in pylsd-nova's readme file which you can try.

**Comment by n0spaces** [comment]
Thanks! Yeah I know there's a lot that can be improved, I just haven't gotten around to it yet.

Closing as I updated requirements.txt and uploaded a new release to pypi.
