### ISSUE TITLE
Very cool library.

### ISSUE THREAD

**Issue by LewisTehMinerz** [n0spaces/get-stick-bugged-lol#4]
This library was the basis for my Discord bot. Whilst I use a modified version of it (mainly for extra features in the bot itself) the core generation stuff is still the original code.

I must say, very cool! Thank you for the work you've done on it!

**Comment by n0spaces** [comment]
Thanks, I'm glad someone found it useful!

Do you have a link to that bot? I'd love to try it out.

**Comment by LewisTehMinerz** [comment]
Sure thing, there's a bot listing here: https://discord.bots.gg/bots/745342388997718077

**Comment by n0spaces** [comment]
Cool, thanks again!
