### ISSUE TITLE
No audio for generated .mp4s (OSX 10.15.6) 

### ISSUE THREAD

**Issue by thedmeyer** [n0spaces/get-stick-bugged-lol#5]
It appears that there is no audio attached for .mp4s generated on OSX.

**Comment by n0spaces** [comment]
Fixed, looks like I had to manually set some audio codec stuff: https://github.com/Zulko/moviepy/issues/820#issuecomment-399301560

I uploaded the update to PyPI, so try upgrading to see if it works now.

    python3 -m pip install --upgrade get-stick-bugged-lol
